name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Node.js ${{ matrix.node }} - Redis ${{ matrix.redis }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
        - 16
        - 18
        - 20
        - 22
        - 24
        redis:
        - 4
        - 5
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: Install
      run: npm install
    - name: Install correct redis version
      run: npm install redis@${{ matrix.redis }}
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test-cover
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: node-${{ matrix.node }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Submit coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
